// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_1
#define IOD_SYMBOL_1
    iod_define_number_symbol(1)
#endif

#ifndef IOD_SYMBOL_2
#define IOD_SYMBOL_2
    iod_define_number_symbol(2)
#endif

#ifndef IOD_SYMBOL_a
#define IOD_SYMBOL_a
    iod_define_symbol(a)
#endif

#ifndef IOD_SYMBOL_age
#define IOD_SYMBOL_age
    iod_define_symbol(age)
#endif

#ifndef IOD_SYMBOL_age2
#define IOD_SYMBOL_age2
    iod_define_symbol(age2)
#endif

#ifndef IOD_SYMBOL_as
#define IOD_SYMBOL_as
    iod_define_symbol(as)
#endif

#ifndef IOD_SYMBOL_avg
#define IOD_SYMBOL_avg
    iod_define_symbol(avg)
#endif

#ifndef IOD_SYMBOL_b
#define IOD_SYMBOL_b
    iod_define_symbol(b)
#endif

#ifndef IOD_SYMBOL_c
#define IOD_SYMBOL_c
    iod_define_symbol(c)
#endif

#ifndef IOD_SYMBOL_children
#define IOD_SYMBOL_children
    iod_define_symbol(children)
#endif

#ifndef IOD_SYMBOL_city
#define IOD_SYMBOL_city
    iod_define_symbol(city)
#endif

#ifndef IOD_SYMBOL_cp
#define IOD_SYMBOL_cp
    iod_define_symbol(cp)
#endif

#ifndef IOD_SYMBOL_d
#define IOD_SYMBOL_d
    iod_define_symbol(d)
#endif

#ifndef IOD_SYMBOL_json_key
#define IOD_SYMBOL_json_key
    iod_define_symbol(json_key)
#endif

#ifndef IOD_SYMBOL_json_skip
#define IOD_SYMBOL_json_skip
    iod_define_symbol(json_skip)
#endif

#ifndef IOD_SYMBOL_my_json_name
#define IOD_SYMBOL_my_json_name
    iod_define_symbol(my_json_name)
#endif

#ifndef IOD_SYMBOL_name
#define IOD_SYMBOL_name
    iod_define_symbol(name)
#endif

#ifndef IOD_SYMBOL_on
#define IOD_SYMBOL_on
    iod_define_symbol(on)
#endif

#ifndef IOD_SYMBOL_opt1
#define IOD_SYMBOL_opt1
    iod_define_symbol(opt1)
#endif

#ifndef IOD_SYMBOL_opt2
#define IOD_SYMBOL_opt2
    iod_define_symbol(opt2)
#endif

#ifndef IOD_SYMBOL_opt3
#define IOD_SYMBOL_opt3
    iod_define_symbol(opt3)
#endif

#ifndef IOD_SYMBOL_optional
#define IOD_SYMBOL_optional
    iod_define_symbol(optional)
#endif

#ifndef IOD_SYMBOL_person
#define IOD_SYMBOL_person
    iod_define_symbol(person)
#endif

#ifndef IOD_SYMBOL_sum
#define IOD_SYMBOL_sum
    iod_define_symbol(sum)
#endif

#ifndef IOD_SYMBOL_username
#define IOD_SYMBOL_username
    iod_define_symbol(username)
#endif

